baseURL = 'https://aaaooai.github.io/'
languageCode = 'ja-jp'
title = '>&1'
theme = "shibui"

[markup]
  [markup.highlight]
    style = "emacs"
    # style = "borland"

[params]
  email = "minazukijiro@gmail.com"

[params.author]
  name = "ﾀﾅｶ ﾄﾓｱｷ"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "https://aaaooai.github.io/aboutme/"
    weight = 2
