baseURL = 'https://aaaooai.github.io/'
languageCode = 'ja-jp'
title = '>&1'
theme = "shibui"

[params]
  author = "ﾀﾅｶ ﾄﾓｱｷ"
  email = "minazukijiro@gmail.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "https://aaaooai.github.io/aboutme/"
    weight = 2
