baseURL = 'https://aaaooai.github.io/'
languageCode = 'ja-jp'
title = '>&1'
theme = "shibui"

[markup]
  [markup.highlight]
    style = "emacs"

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = "posts"
    pageRef = "/posts"
    weight = 20

  [[menus.main]]
    name = "tags"
    pageRef = "/tags"
    weight = 30

  [[menus.main]]
    name = "about"
    pageRef = "/about"
    weight = 40
